# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.2.5
_src_path: https://github.com/jupyterlab/extension-template
author_email: mhilmy@hey.com
author_name: Muhammad Aditya Hilmy
has_binder: false
has_settings: false
kind: server
labextension_name: rucio-jupyterlab
project_short_description: JupyterLab extension for integrating Rucio
python_name: rucio_jupyterlab
repository: https://github.com/rucio/jupyterlab-extension.git
test: true

